<?php

use App\Models\Article;

return [
    'disk' => env('MEDIA_S3_DISK', 's3'),
    's3_prefix' => trim((string) env('MEDIA_S3_PREFIX', ''), '/'),
    'multipart_threshold_bytes' => (int) env('MEDIA_UPLOAD_MULTIPART_THRESHOLD_BYTES', 16 * 1024 * 1024),
    'part_size_bytes' => max(5 * 1024 * 1024, (int) env('MEDIA_UPLOAD_PART_SIZE_BYTES', 8 * 1024 * 1024)),
    'session_ttl_minutes' => (int) env('MEDIA_UPLOAD_SESSION_TTL_MINUTES', 60),
    'download_url_ttl_minutes' => (int) env('MEDIA_DOWNLOAD_URL_TTL_MINUTES', 5),
    'scan_fail_closed' => filter_var(env('MEDIA_SCAN_FAIL_CLOSED', true), FILTER_VALIDATE_BOOL),
    'scan_driver' => env('MEDIA_SCAN_DRIVER', 'clamav'),
    'clamav_binary' => env('CLAMAV_SCAN_BINARY', '/usr/bin/clamdscan'),
    'max_active_sessions_per_user' => (int) env('MEDIA_UPLOAD_MAX_ACTIVE_SESSIONS_PER_USER', 10),
    'rate_limit_per_minute' => max(150, (int) env('MEDIA_UPLOAD_RATE_LIMIT_PER_MINUTE', 150)),
    'presign_ttl_minutes' => min(5, (int) env('MEDIA_UPLOAD_PRESIGN_TTL_MINUTES', 5)),
    'queues' => [
        'scan' => env('MEDIA_SCAN_QUEUE', 'media-scan'),
        'migration' => env('MEDIA_MIGRATION_QUEUE', 'media-migration'),
    ],

    'prefixes' => [
        'incoming' => 'incoming/',
        'legacy' => 'incoming/legacy/',
        'quarantine' => 'quarantine/',
        'temporary' => 'temporary/',
    ],

    'purposes' => [
        'article_manuscript' => [
            'model' => Article::class,
            'target' => 'article',
            'allow_detached' => true,
            'article_file_type' => 'manuscript',
            'clean_prefix' => 'clean/articles/original/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'extensions' => ['pdf', 'doc', 'docx'],
            'scan_required' => true,
        ],
        'article_revision' => [
            'model' => Article::class,
            'target' => 'article',
            'allow_detached' => true,
            'article_file_type' => 'manuscript',
            'clean_prefix' => 'clean/articles/revisions/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'extensions' => ['pdf', 'doc', 'docx'],
            'scan_required' => true,
        ],
        'article_supplementary' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'supplementary',
            'clean_prefix' => 'clean/articles/supplementary/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => [
                'application/pdf',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/plain',
                'text/csv',
                'image/png',
                'image/jpeg',
                'image/webp',
            ],
            'extensions' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
            'create_article_asset' => true,
            'asset_type' => 'supplementary',
        ],
        'article_image' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'supplementary',
            'clean_prefix' => 'clean/articles/images/',
            'max_size_bytes' => 10 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
            'create_article_asset' => true,
            'asset_type' => 'image',
        ],
        'article_production_file' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'copy_edited_file',
            'clean_prefix' => 'clean/articles/production/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'extensions' => ['pdf', 'doc', 'docx'],
            'scan_required' => true,
        ],
        'article_plagiarism_report' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'plagiarism_report',
            'clean_prefix' => 'clean/articles/plagiarism/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'],
            'extensions' => ['pdf', 'doc', 'docx', 'txt'],
            'scan_required' => true,
        ],
        'article_annotated_manuscript' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'annotated_manuscript',
            'clean_prefix' => 'clean/articles/annotations/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'extensions' => ['pdf', 'doc', 'docx'],
            'scan_required' => true,
        ],
        'article_reviewed_manuscript' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'reviewed_manuscript',
            'clean_prefix' => 'clean/articles/reviews/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'extensions' => ['pdf', 'doc', 'docx'],
            'scan_required' => true,
        ],
        'article_proof_file' => [
            'model' => Article::class,
            'target' => 'article',
            'article_file_type' => 'proof_file',
            'clean_prefix' => 'clean/articles/proofs/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf'],
            'extensions' => ['pdf'],
            'scan_required' => true,
        ],
        'article_published_pdf' => [
            'model' => Article::class,
            'target' => 'article',
            'allow_detached' => true,
            'article_file_type' => 'publication_pdf',
            'clean_prefix' => 'clean/articles/published/',
            'max_size_bytes' => 25 * 1024 * 1024,
            'detected_mime_types' => ['application/pdf'],
            'extensions' => ['pdf'],
            'scan_required' => true,
        ],
        'article_featured_image' => [
            'target' => 'reference',
            'clean_prefix' => 'clean/articles/featured/',
            'max_size_bytes' => 5 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'magazine_cover' => [
            'target' => 'reference',
            'clean_prefix' => 'clean/magazines/covers/',
            'max_size_bytes' => 5 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'issue_cover' => [
            'target' => 'reference',
            'clean_prefix' => 'clean/magazines/issues/',
            'max_size_bytes' => 5 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'cms_image' => [
            'target' => 'media',
            'clean_prefix' => 'clean/cms/',
            'max_size_bytes' => 10 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'profile_image' => [
            'target' => 'user',
            'clean_prefix' => 'clean/profiles/',
            'max_size_bytes' => 5 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'publication_section_image' => [
            'target' => 'reference',
            'clean_prefix' => 'clean/articles/publication-sections/',
            'max_size_bytes' => 8 * 1024 * 1024,
            'detected_mime_types' => ['image/png', 'image/jpeg', 'image/webp'],
            'extensions' => ['png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
        'support_ticket_attachment' => [
            'target' => 'reference',
            'clean_prefix' => 'clean/support/tickets/',
            'max_size_bytes' => 10 * 1024 * 1024,
            'detected_mime_types' => [
                'application/pdf',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/plain',
                'text/csv',
                'image/png',
                'image/jpeg',
                'image/webp',
            ],
            'extensions' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'png', 'jpg', 'jpeg', 'webp'],
            'scan_required' => true,
        ],
    ],
];
