<?php

$template = static fn (
    string $category,
    string $priority,
    string $severity,
    string $title,
    string $body,
    ?string $route = null,
    bool $action = false,
    bool $mandatoryEmail = false,
    bool $legacyEmail = false,
): array => compact('category', 'priority', 'severity', 'title', 'body', 'route', 'action', 'mandatoryEmail', 'legacyEmail') + [
    'version' => 1,
    'schemaVersion' => 1,
    'allowedRenderData' => ['tracking_code', 'publication', 'article_title', 'ticket_reference', 'due_at'],
    'emailSubject' => $title,
    'emailBody' => $body,
    'mandatoryChannels' => $mandatoryEmail ? ['in_app', 'email'] : [],
    'optionalChannels' => $mandatoryEmail ? [] : ['in_app', 'email'],
    'actionKey' => $action ? 'open_existing_workflow' : null,
];

return [
    'features' => [
        'enabled' => env('NOTIFICATIONS_ENABLED', true),
        'in_app' => env('NOTIFICATIONS_IN_APP_ENABLED', true),
        'email_projection' => env('NOTIFICATIONS_EMAIL_PROJECTION_ENABLED', true),
        'digests' => env('NOTIFICATIONS_DIGESTS_ENABLED', true),
        'reminders' => env('NOTIFICATIONS_REMINDERS_ENABLED', true),
    ],
    'outbox' => [
        'chunk_size' => 100,
        'stale_after_minutes' => 10,
        'max_attempts' => 5,
        'recovery_backoff_minutes' => [1, 5, 15, 60, 240],
    ],
    'categories' => ['security', 'assignment', 'deadline', 'editorial', 'revision', 'files', 'production', 'publication', 'support', 'system'],
    'priorities' => ['critical', 'high', 'normal', 'low'],
    'severities' => ['error', 'warning', 'success', 'info'],
    'privacy_variants' => ['author', 'co_author', 'reviewer', 'assignee', 'sub_editor', 'editor', 'publisher', 'admin', 'assigner', 'support_owner', 'support_staff', 'account'],
    'subject_types' => ['article', 'sub_editor_assignment', 'reviewer_assignment', 'production_assignment', 'support_ticket', 'article_version', 'accepted_file_set', 'article_file', 'issue', 'user'],
    'routes' => [
        'article.workflow', 'article.edit', 'editor.desk', 'sub_editor.desk', 'reviewer.desk',
        'copy_editor.desk', 'publisher.desk', 'issue.manager', 'support.ticket', 'admin.support.ticket',
        'account.settings', 'notifications.center', 'article.public', 'direct.publication',
    ],
    'preferences' => [
        'security' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'assignment' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'deadline' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'editorial' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'revision' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'files' => ['in_app' => true, 'email' => 'digest', 'locked' => false],
        'production' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'publication' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'support' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
        'system' => ['in_app' => true, 'email' => 'immediate', 'locked' => false],
    ],
    'templates' => [
        'direct_publication.created' => $template('publication', 'normal', 'info', 'Direct-publication draft created', 'Direct-publication draft {tracking_code} was created.', 'direct.publication'),
        'direct_publication.ready' => $template('publication', 'high', 'success', 'Direct publication ready', 'Article {tracking_code} is ready for direct publication.', 'direct.publication', true, true),
        'direct_publication.scheduled' => $template('publication', 'high', 'info', 'Direct publication scheduled', 'Article {tracking_code} was scheduled for publication.', 'direct.publication', true, true),
        'direct_publication.published' => $template('publication', 'high', 'success', 'Article published', 'Article {tracking_code} has been published.', 'article.public', false, true),
        'direct_publication.unpublished' => $template('publication', 'critical', 'warning', 'Article unpublished', 'Article {tracking_code} has been unpublished.', 'direct.publication', true, true),
        'direct_publication.file_replaced' => $template('files', 'high', 'warning', 'Public file replaced', 'A public file for article {tracking_code} was replaced.', 'direct.publication', true),
        'direct_publication.metadata_corrected' => $template('publication', 'normal', 'info', 'Publication metadata corrected', 'Publication metadata for article {tracking_code} was corrected.', 'direct.publication'),
        'article.submitted' => $template('editorial', 'high', 'info', 'Manuscript submitted', 'Manuscript {tracking_code} has been submitted to {publication}.', 'article.workflow', false, true, true),
        'article.desk_rejected' => $template('editorial', 'high', 'warning', 'Editorial decision recorded', 'A desk decision has been recorded for manuscript {tracking_code}.', 'article.workflow', false, true),
        'article.under_review' => $template('editorial', 'normal', 'info', 'Manuscript under review', 'Manuscript {tracking_code} has entered editorial review.', 'article.workflow', false, false, true),
        'transfer.requested' => $template('editorial', 'high', 'info', 'Transfer requested', 'A publication transfer was requested for manuscript {tracking_code}.', 'article.workflow', true, true, true),
        'transfer.accepted' => $template('editorial', 'high', 'success', 'Transfer accepted', 'The publication transfer for manuscript {tracking_code} was accepted.', 'article.workflow', false, true, true),
        'transfer.rejected' => $template('editorial', 'high', 'warning', 'Transfer declined', 'The publication transfer for manuscript {tracking_code} was declined.', 'article.workflow', false, true, true),
        'sub_editor.assigned' => $template('assignment', 'high', 'info', 'Sub-editor assignment', 'A sub-editor assignment for manuscript {tracking_code} requires attention.', 'article.workflow', true, true, true),
        'sub_editor.recommendation_submitted' => $template('editorial', 'high', 'success', 'Recommendation submitted', 'A sub-editor recommendation is ready for manuscript {tracking_code}.', 'article.workflow', true, true, true),
        'reviewer.invited' => $template('assignment', 'high', 'info', 'Review invitation sent', 'A review invitation for manuscript {tracking_code} is awaiting a response.', 'reviewer.desk', true, true, true),
        'reviewer.assigned' => $template('assignment', 'normal', 'info', 'Reviewer invitation created', 'A reviewer invitation was created for manuscript {tracking_code}.', 'article.workflow', false, false, true),
        'review.accepted' => $template('assignment', 'high', 'success', 'Review invitation accepted', 'A review invitation for manuscript {tracking_code} was accepted.', 'article.workflow', false, true, true),
        'review.declined' => $template('assignment', 'high', 'warning', 'Review invitation declined', 'A review invitation for manuscript {tracking_code} was declined.', 'article.workflow', true, true, true),
        'review.invitation_reminded' => $template('deadline', 'normal', 'info', 'Review invitation reminder sent', 'The review invitation for manuscript {tracking_code} is still awaiting a response.', 'reviewer.desk', true, false, true),
        'review.invitation_expired' => $template('deadline', 'high', 'warning', 'Review invitation expired', 'A review invitation for manuscript {tracking_code} expired.', 'article.workflow', true, true),
        'review.submitted' => $template('editorial', 'high', 'success', 'Review submitted', 'A review is ready for manuscript {tracking_code}.', 'article.workflow', true, true, true),
        'review.reopened' => $template('assignment', 'high', 'warning', 'Review reopened', 'A review for manuscript {tracking_code} was reopened.', 'reviewer.desk', true, true, true),
        'revision.requested' => $template('revision', 'high', 'warning', 'Revision required', 'Revisions are required for manuscript {tracking_code}.', 'article.edit', true, true, true),
        'article.resubmitted' => $template('revision', 'high', 'success', 'Revised manuscript submitted', 'A revised version of manuscript {tracking_code} is ready.', 'article.workflow', true, true, true),
        'article.version_created' => $template('revision', 'normal', 'info', 'Manuscript version created', 'A new version is available for manuscript {tracking_code}.', 'article.workflow'),
        'article.accepted' => $template('editorial', 'high', 'success', 'Manuscript accepted', 'Manuscript {tracking_code} has been accepted.', 'article.workflow', false, true, true),
        'article.rejected' => $template('editorial', 'high', 'warning', 'Editorial decision recorded', 'An editorial decision has been recorded for manuscript {tracking_code}.', 'article.workflow', false, true, true),
        'accepted_file_set.created' => $template('files', 'high', 'success', 'Accepted files ready', 'The accepted file set for manuscript {tracking_code} is ready.', 'article.workflow', true, true),
        'accepted_file_set.superseded' => $template('files', 'high', 'warning', 'Accepted files replaced', 'The accepted file set for manuscript {tracking_code} was replaced.', 'article.workflow', true),
        'article_file.available' => $template('files', 'normal', 'success', 'Workflow file available', 'A required file for manuscript {tracking_code} is available.', 'article.workflow'),
        'article_file.rejected' => $template('files', 'high', 'error', 'File upload rejected', 'A file for manuscript {tracking_code} could not be accepted.', 'article.workflow', true, true),
        'production.assigned' => $template('production', 'high', 'info', 'Copyediting assignment', 'Copyediting for manuscript {tracking_code} requires attention.', 'article.workflow', true, true, true),
        'production.completed' => $template('production', 'high', 'success', 'Copyediting completed', 'Copyediting for manuscript {tracking_code} is complete.', 'article.workflow', false, true, true),
        'author.final_review_requested' => $template('production', 'high', 'warning', 'Publication approval required', 'Your final approval is required for manuscript {tracking_code}.', 'article.workflow', true, true, true),
        'author.final_review_reminder' => $template('deadline', 'high', 'warning', 'Final approval reminder', 'Final approval for manuscript {tracking_code} is due soon.', 'article.workflow', true, true),
        'author.final_review_denied' => $template('production', 'high', 'warning', 'Returned to copyediting', 'Manuscript {tracking_code} was returned to copyediting.', 'article.workflow', true, true, true),
        'author.final_review_approved' => $template('production', 'high', 'success', 'Publication approved', 'Final publication approval was recorded for manuscript {tracking_code}.', 'article.workflow', false, true, true),
        'author.final_review_auto_approved' => $template('production', 'high', 'warning', 'Publication automatically approved', 'The response window for manuscript {tracking_code} expired and approval was recorded.', 'article.workflow', false, true, true),
        'article.ready_for_publication' => $template('publication', 'high', 'success', 'Ready for publication', 'Manuscript {tracking_code} is ready for publication.', 'publisher.desk', true, true, true),
        'article.issue_assigned' => $template('publication', 'normal', 'info', 'Issue assignment updated', 'Manuscript {tracking_code} was assigned to an issue.', 'issue.manager'),
        'issue.published' => $template('publication', 'normal', 'success', 'Issue published', 'An issue containing manuscript {tracking_code} was published.', 'issue.manager'),
        'article.published' => $template('publication', 'high', 'success', 'Article published', 'Article {tracking_code} has been published.', 'article.public', false, true, true),
        'post_publication.recorded' => $template('publication', 'critical', 'warning', 'Post-publication action recorded', 'A post-publication action was recorded for article {tracking_code}.', 'article.workflow', false, true, true),
        'deadline.due_in_3_days' => $template('deadline', 'normal', 'warning', 'Assignment due in 3 days', 'An assignment for manuscript {tracking_code} is due in 3 days.', 'article.workflow', true),
        'deadline.due_today' => $template('deadline', 'high', 'warning', 'Assignment due today', 'An assignment for manuscript {tracking_code} is due today.', 'article.workflow', true, true),
        'deadline.overdue_3_days' => $template('deadline', 'high', 'error', 'Assignment overdue', 'An assignment for manuscript {tracking_code} is 3 days overdue.', 'article.workflow', true, true),
        'deadline.changed' => $template('deadline', 'high', 'info', 'Assignment deadline changed', 'The deadline for manuscript {tracking_code} changed.', 'article.workflow', true, true),
        'support.ticket_created' => $template('support', 'high', 'info', 'Support ticket created', 'Support ticket {ticket_reference} was created.', 'support.ticket', true, true, true),
        'support.ticket_replied' => $template('support', 'high', 'info', 'New support reply', 'A new reply was added to support ticket {ticket_reference}.', 'support.ticket', true, true, true),
        'support.ticket_status_changed' => $template('support', 'normal', 'info', 'Support ticket updated', 'Support ticket {ticket_reference} changed status.', 'support.ticket', false, true, true),
        'account.password_changed' => $template('security', 'critical', 'warning', 'Password changed', 'Your ScholarlyNest password was changed.', 'account.settings', false, true, true),
        'account.email_changed' => $template('security', 'critical', 'warning', 'Email address changed', 'Your ScholarlyNest email address was changed.', 'account.settings', false, true),
        'account.mfa_method_changed' => $template('security', 'critical', 'warning', 'Multi-factor authentication changed', 'Your multi-factor authentication settings changed.', 'account.settings', false, true),
        'account.role_or_scope_changed' => $template('security', 'high', 'warning', 'Account access changed', 'Your ScholarlyNest role or publication access changed.', 'account.settings', false, true),
        'account.impersonation_started' => $template('security', 'critical', 'warning', 'Impersonation session started', 'An administrator impersonation session was started for your account.', 'account.settings'),
        'account.impersonation_stopped' => $template('security', 'critical', 'info', 'Impersonation session ended', 'An administrator impersonation session for your account ended.', 'account.settings'),
    ],
];
